# Generated by Django 6.1.1 on 2026-09-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.CharField(max_length=64, unique=True)),
                ('org_id', models.CharField(max_length=64)),
                ('location_name', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'indexes': [models.Index(fields=['org_id'], name='reconciler__org_id_af7f82_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemARecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(max_length=128)),
                ('record_id_normalized', models.CharField(db_index=True, max_length=128)),
                ('location_id_raw', models.CharField(blank=True, default='', max_length=128)),
                ('event_date_raw', models.CharField(blank=True, default='', max_length=64)),
                ('category_code', models.CharField(blank=True, default='', max_length=64)),
                ('actor_id', models.CharField(blank=True, default='', max_length=64)),
                ('base_value_raw', models.CharField(blank=True, default='', max_length=64)),
                ('adjustment_raw', models.CharField(blank=True, default='', max_length=64)),
                ('total_value_raw', models.CharField(blank=True, default='', max_length=64)),
                ('state', models.CharField(blank=True, default='', max_length=64)),
                ('raw_row', models.JSONField(default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['record_id_normalized'], name='reconciler__record__778801_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemBEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.CharField(max_length=128)),
                ('record_ref_raw', models.CharField(blank=True, default='', max_length=128)),
                ('record_ref_normalized', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('location_id_raw', models.CharField(blank=True, default='', max_length=128)),
                ('recorded_on_raw', models.CharField(blank=True, default='', max_length=64)),
                ('value_raw', models.CharField(blank=True, default='', max_length=64)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('raw_row', models.JSONField(default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['record_ref_normalized'], name='reconciler__record__384de3_idx')],
            },
        ),
    ]
